### ISSUE TITLE
Easy way to plot all series

### ISSUE THREAD

**Issue by aurrelhebert** [LostInBrittany/warp10-photon#27]
How can we plot all series returned by a single request on Photon ?
(With or without the 'a' touch of a keyboard)

**Comment by aurrelhebert** [comment]
To repoduce the error execute this script: http://photon.metrics.ovh.net/#/permalink/WyAxIDIwIDwlIE5FV0dUUyAwIE5hTiBOYU4gTmFOIDEgQUREVkFMVUUgMiBOYU4gTmFOIE5hTiAxMCBBRERWQUxVRSAlPiBGT1IgXSA%3D/eyJ1cmwiOiJodHRwczovL3dhcnAxMC5ncmExLW92aC5tZXRyaWNzLm92aC5uZXQvYXBpL3YwIn0%3D

And try to plot all result pressing 'a'

**Comment by LostInBrittany** [comment]
OK, it seems the error happen when you have a mixed array with time series and not time series entries...

http://photon.metrics.ovh.net/#/permalink/WyAxIE5FV0dUUyAwIE5hTiBOYU4gTmFOIDEgQUREVkFMVUUgMiBOYU4gTmFOIE5hTiAxMCBBRERWQUxVRSBdIA%3D%3D/eyJ1cmwiOiJodHRwczovL3dhcnAxMC5ncmExLW92aC5tZXRyaWNzLm92aC5uZXQvYXBpL3YwIn0%3D

Going to dig to find why...
